installing npm

diff --git a/.github/workflows/laravel.yml b/.github/workflows/laravel.yml
--- a/.github/workflows/laravel.yml
+++ b/.github/workflows/laravel.yml
@@ -209,18 +209,6 @@ jobs:
     runs-on: ubuntu-latest
     needs: [web-deploy, ssh-release, run-befor-hook]
     steps:
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: "21.7.2"
-
-      - name: Install Node.js Dependencies
-        run: npm install
-
-      - name: Build Assets
-        run: npm run build
-        
       - name: run-activate-release
         uses: appleboy/ssh-action@master
         env:
@@ -247,6 +235,48 @@ jobs:
               ls -la $ACTIVE_RELEASE_PATH
               cd $ACTIVE_RELEASE_PATH || { echo "Failed to cd into release path"; exit 1; }
               composer install --no-dev --optimize-autoloader
+  
+  
+  # Run node
+  run-node:
+    name: run-node
+    runs-on: ubuntu-latest
+    needs: [web-deploy, ssh-release, run-befor-hook, activate-release]
+    steps:
+      - name: run-node
+        uses: appleboy/ssh-action@master
+        env:
+          GITHUB_SHA: ${{ github.sha }}
+          RELEASE_PATH: /home/printsh1/printshopeld/release/${{github.sha}}
+          LINK_RELEASE_PATH: /home/printsh1/public_html
+          ACTIVE_RELEASE_PATH: /home/printsh1/printshopeld/current
+          STORAGE_PATH: /home/printsh1/printshopeld/storage
+          BASE_PATH: /home/printsh1/printshopeld
+          LARAVEL_ENV: ${{ secrets.LARAVEL_ENV }}
+        with:
+          host: ${{ secrets.SSH_SITES_IP }}
+          username: ${{ secrets.FTP_SITES_USER }}
+          password: ${{ secrets.FTP_SITES_PASSWORD }}
+          port: ${{ secrets.SSH_SITES_PORT }}
+          envs: GITHUB_SHA,RELEASE_PATH,ACTIVE_RELEASE_PATH,STORAGE_PATH,BASE_PATH,LARAVEL_ENV,LINK_RELEASE_PATH
+          # in the event of trouble recognizing the changes after the link find a solytion to refresh
+          script: |
+              ls -la $ACTIVE_RELEASE_PATH
+              cd $ACTIVE_RELEASE_PATH || { echo "Failed to cd into release path"; exit 1; }
+              
+              echo "Setting up Node.js environment..."
+              curl -fsSL https://deb.nodesource.com/setup_21.x | bash - || { echo "Failed to add NodeSource repository"; exit 1; }
+              apt-get install -y nodejs || { echo "Failed to install Node.js"; exit 1; }
+              
+              node -v
+              npm -v
+              
+              echo "Installing Node.js dependencies..."
+              npm install || { echo "Failed to install Node.js dependencies"; exit 1; }
+
+              # Build front-end assets
+              echo "Building front-end assets..."
+              npm run build || { echo "Failed to build assets"; exit 1; }
   
   # # Run Migrations release
   # migrations-run:
