upload artifact

diff --git a/.github/workflows/laravel.yml b/.github/workflows/laravel.yml
--- a/.github/workflows/laravel.yml
+++ b/.github/workflows/laravel.yml
@@ -82,3 +82,232 @@ jobs:
           port: ${{ secrets.SSH_SITES_PORT }}
           source: ${{ github.sha}}.tar.gz
           target: /home/printsh1/printshopeld/artifacts
+      - name: extract archive and create directory
+        uses: appleboy/ssh-action@master
+        env:
+          GITHUB_SHA: ${{ github.sha }}
+
+          SOURCE_ASSET_DIR: /home/printsh1/printshopeld/release/${{github.sha}}/public/assets
+          SOURCE_ADMIN_DIR: /home/printsh1/printshopeld/release/${{github.sha}}/public/admin
+          SOURCE_BUILD_DIR: /home/printsh1/printshopeld/release/${{github.sha}}/public/build
+
+          DEST_ASSET_DIR: /home/printsh1/public_html/assets
+          DEST_ADMIN_DIR: /home/printsh1/public_html/admin
+          DEST_BUILD_DIR: /home/printsh1/public_html/build
+
+          DEST_PARENT_DIR: /home/printsh1/public_html
+        with:
+          host: ${{ secrets.SSH_SITES_IP }}
+          username: ${{ secrets.FTP_SITES_USER }}
+          password: ${{ secrets.FTP_SITES_PASSWORD }}
+          port: ${{ secrets.SSH_SITES_PORT }}
+          envs: GITHUB_SHA,SOURCE_ASSET_DIR,SOURCE_ADMIN_DIR,SOURCE_BUILD_DIR,DEST_ASSET_DIR,DEST_ADMIN_DIR,DEST_BUILD_DIR,DEST_PARENT_DIR
+          script: |
+            mkdir -p "/home/printsh1/printshopeld/release/${GITHUB_SHA}"
+            tar xzf /home/printsh1/printshopeld/artifacts/${GITHUB_SHA}.tar.gz -C "/home/printsh1/printshopeld/release/${GITHUB_SHA}"
+            # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+            rm -rf /home/printsh1/printshopeld/release/${GITHUB_SHA}/storage
+            # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+            if [ ! -d "/home/printsh1/printshopeld/storage" ]; then
+            mkdir -p /home/printsh1/printshopeld/storage/{app,public,framework,logs}
+            mkdir -p /home/printsh1/printshopeld/storage/framework/{cache,sessions,testing,views}
+            mkdir -p /home/printsh1/printshopeld/storage/framework/cache/data
+            chmod -R 0777 /home/printsh1/printshopeld/storage
+            fi
+            # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+            if [ -d "$SOURCE_ASSET_DIR" ]; then
+                if [ -d "$DEST_ASSET_DIR" ]; then
+                    rm -rf "$DEST_ASSET_DIR"
+                    if [ $? -ne 0 ]; then
+                        echo "Failed to remove the destination asset directory."
+                        exit 1
+                    fi
+                else
+                    echo "asset directory does not exist in the destination."
+                fi
+                mv "$SOURCE_ASSET_DIR" "$DEST_PARENT_DIR"
+                if [ $? -ne 0 ]; then
+                    echo "Failed to move the asset directory from source to destination."
+                    exit 1
+                fi
+            else
+                echo "asset directory does not exist in the source."
+            fi
+            # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+            if [ -d "$SOURCE_ADMIN_DIR" ]; then
+                if [ -d "$DEST_ADMIN_DIR" ]; then
+                    rm -rf "$DEST_ADMIN_DIR"
+                    if [ $? -ne 0 ]; then
+                        echo "Failed to remove the destination admin directory."
+                        exit 1
+                    fi
+                else
+                    echo "admin directory does not exist in the destination."
+                fi
+                mv "$SOURCE_ADMIN_DIR" "$DEST_PARENT_DIR"
+                if [ $? -ne 0 ]; then
+                    echo "Failed to move the admin directory from source to destination."
+                    exit 1
+                fi
+            else
+                echo "admin directory does not exist in the source."
+            fi
+            # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+            if [ -d "$SOURCE_BUILD_DIR" ]; then
+                if [ -d "$DEST_BUILD_DIR" ]; then
+                    rm -rf "$DEST_BUILD_DIR"
+                    if [ $? -ne 0 ]; then
+                        echo "Failed to remove the destination build directory."
+                        exit 1
+                    fi
+                else
+                    echo "build directory does not exist in the destination."
+                fi
+                mv "$SOURCE_BUILD_DIR" "$DEST_PARENT_DIR"
+                if [ $? -ne 0 ]; then
+                    echo "Failed to move the build directory from source to destination."
+                    exit 1
+                fi
+            else
+                echo "build directory does not exist in the source."
+            fi
+            # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+            mv -f "/home/printsh1/printshopeld/release/${GITHUB_SHA}/public/.htaccess" "/home/printsh1/public_html"
+            mv -f "/home/printsh1/printshopeld/release/${GITHUB_SHA}/public/favican.ico" "/home/printsh1/public_html"
+            mv -f "/home/printsh1/printshopeld/release/${GITHUB_SHA}/public/index.php" "/home/printsh1/public_html"
+            mv -f "/home/printsh1/printshopeld/release/${GITHUB_SHA}/public/robots.txt" "/home/printsh1/public_html"
+            # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+            rm -rf /home/printsh1/printshopeld/release/${GITHUB_SHA}/public/
+            # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+
+  # Run befor-hooks
+  run-befor-hook:
+    name: befor-hook
+    runs-on: ubuntu-latest
+    needs: [web-deploy, ssh-release]
+    steps:
+      - name: run-befor-hooks
+        uses: appleboy/ssh-action@master
+        env:
+          GITHUB_SHA: ${{ github.sha }}
+          RELEASE_PATH: /home/printsh1/printshopeld/release/${{github.sha}}
+          ACTIVE_RELEASE_PATH: /home/printsh1/printshopeld/current
+          STORAGE_PATH: /home/printsh1/printshopeld/storage
+          BASE_PATH: /home/printsh1/printshopeld
+        with:
+          host: ${{ secrets.SSH_SITES_IP }}
+          username: ${{ secrets.FTP_SITES_USER }}
+          password: ${{ secrets.FTP_SITES_PASSWORD }}
+          port: ${{ secrets.SSH_SITES_PORT }}
+          envs: GITHUB_SHA,RELEASE_PATH,ACTIVE_RELEASE_PATH,STORAGE_PATH,BASE_PATH
+          script: |
+            echo "${GITHUB_SHA}"
+  
+  # Run activate release
+  activate-release:
+    name: activate-release
+    runs-on: ubuntu-latest
+    needs: [web-deploy, ssh-release, run-befor-hook]
+    steps:
+      - name: run-activate-release
+        uses: appleboy/ssh-action@master
+        env:
+          GITHUB_SHA: ${{ github.sha }}
+          RELEASE_PATH: /home/printsh1/printshopeld/release/${{github.sha}}
+          LINK_RELEASE_PATH: /home/printsh1/public_html
+          ACTIVE_RELEASE_PATH: /home/printsh1/printshopeld/current
+          STORAGE_PATH: /home/printsh1/printshopeld/storage
+          BASE_PATH: /home/printsh1/printshopeld
+          LARAVEL_ENV: ${{ secrets.LARAVEL_ENV }}
+        with:
+          host: ${{ secrets.SSH_SITES_IP }}
+          username: ${{ secrets.FTP_SITES_USER }}
+          password: ${{ secrets.FTP_SITES_PASSWORD }}
+          port: ${{ secrets.SSH_SITES_PORT }}
+          envs: GITHUB_SHA,RELEASE_PATH,ACTIVE_RELEASE_PATH,STORAGE_PATH,BASE_PATH,LARAVEL_ENV,LINK_RELEASE_PATH
+          # in the event of trouble recognizing the changes after the link find a solytion to refresh
+          script: |
+            printf "%s" "$LARAVEL_ENV" > "${BASE_PATH}/.env"
+            ln -s -n -f ${BASE_PATH}/.env $RELEASE_PATH
+            ln -s -n -f $STORAGE_PATH $RELEASE_PATH
+            ln -s -n -f $RELEASE_PATH $ACTIVE_RELEASE_PATH
+            ln -s -n -f $STORAGE_PATH $LINK_RELEASE_PATH
+  
+  # Run Migrations release
+  migrations-run:
+    name: migrations-run
+    runs-on: ubuntu-latest
+    needs: [web-deploy, ssh-release, run-befor-hook, activate-release]
+    steps:
+      - name: run-activate-release
+        uses: appleboy/ssh-action@master
+        env:
+          GITHUB_SHA: ${{ github.sha }}
+          RELEASE_PATH: /home/printsh1/printshopeld/release/${{github.sha}}
+          ACTIVE_RELEASE_PATH: /home/printsh1/printshopeld/current
+          STORAGE_PATH: /home/printsh1/printshopeld/storage
+          BASE_PATH: /home/printsh1/printshopeld
+          LARAVEL_ENV: ${{ secrets.LARAVEL_ENV }}
+        with:
+          host: ${{ secrets.SSH_SITES_IP }}
+          username: ${{ secrets.FTP_SITES_USER }}
+          password: ${{ secrets.FTP_SITES_PASSWORD }}
+          port: ${{ secrets.SSH_SITES_PORT }}
+          envs: GITHUB_SHA,RELEASE_PATH,ACTIVE_RELEASE_PATH,STORAGE_PATH,BASE_PATH,LARAVEL_ENV
+          # in the event of trouble recognizing the changes after the link find a solytion to refresh
+          script: |
+            cd $ACTIVE_RELEASE_PATH
+            php artisan migrate --force
+            php artisan db:seed
+  
+  # Run activate release
+  run-after-hook:
+    name: after-hook
+    runs-on: ubuntu-latest
+    needs: [web-deploy, ssh-release, run-befor-hook, activate-release, migrations-run]
+    steps:
+      - name: run-after-hooks
+        uses: appleboy/ssh-action@master
+        env:
+          GITHUB_SHA: ${{ github.sha }}
+          RELEASE_PATH: /home/printsh1/printshopeld/release/${{github.sha}}
+          ACTIVE_RELEASE_PATH: /home/printsh1/printshopeld/current
+          STORAGE_PATH: /home/printsh1/printshopeld/storage
+          BASE_PATH: /home/printsh1/printshopeld
+        with:
+          host: ${{ secrets.SSH_SITES_IP }}
+          username: ${{ secrets.FTP_SITES_USER }}
+          password: ${{ secrets.FTP_SITES_PASSWORD }}
+          port: ${{ secrets.SSH_SITES_PORT }}
+          envs: GITHUB_SHA,RELEASE_PATH,ACTIVE_RELEASE_PATH,STORAGE_PATH,BASE_PATH
+          script: |
+            echo "${GITHUB_SHA}"
+  
+  # Run cleanup
+  clean-up:
+    name: Clean-up
+    runs-on: ubuntu-latest
+    needs:
+      [
+        web-deploy,
+        ssh-release,
+        run-befor-hook,
+        activate-release,
+        migrations-run,
+        run-after-hook,
+      ]
+    steps:
+      - name: run-clean-up
+        uses: appleboy/ssh-action@master
+        env:
+          RELEASE_PATH: /home/printsh1/printshopeld/release
+          ARTIFACTS_PATH: /home/printsh1/printshopeld/artifacts
+        with:
+          host: ${{ secrets.SSH_SITES_IP }}
+          username: ${{ secrets.FTP_SITES_USER }}
+          password: ${{ secrets.FTP_SITES_PASSWORD }}
+          port: ${{ secrets.SSH_SITES_PORT }}
+          envs: RELEASE_PATH,ARTIFACTS_PATH
+          script: |
+            cd $RELEASE_PATH && ls -t -1 | tail -n +6 | xargs rm -rf
+            cd $ARTIFACTS_PATH && ls -t -1 | tail -n +6 | xargs rm -rf
